version: '3.8'

services:
  backend:
    build: .
    container_name: personal-library-backend
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/my-personal-library
      - PORT=3000
    depends_on:
      - mongo
    restart: "no"  # impede reinício automático

  mongo:
    image: mongo
    container_name: mongo-local
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
